[provider]
cluster = "localnet" # Use local validator for testing
wallet = "~/.config/solana/id.json" # Wallet path

[programs.localnet]
yozoon = "3J6Hu2iwgwuU4gvQACsHqEsfrRog6EzoaEWo1oZ8NHNx" # Program ID

[programs.devnet]
yozoon = "3J6Hu2iwgwuU4gvQACsHqEsfrRog6EzoaEWo1oZ8NHNx" # Program ID

[toolchain]
package_manager = "yarn"
anchor_version = "0.29.0"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
