[provider]
cluster = "devnet"          # Deployment network
wallet = "~/.config/solana/id.json" # Wallet path

[programs.devnet]
yozoon = "7giegFn7Wy4McS1eKr1cpjhpE9TibEywydG57PSao9bM" # Program ID

[programs.localnet]
yozoon = "7giegFn7Wy4McS1eKr1cpjhpE9TibEywydG57PSao9bM" # Program ID

[toolchain]
package_manager = "yarn"
anchor_version = "0.28.0"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"