version: '3.8'

services:
  validator:
    build: .
    ports:
      - "8899:8899"  # RPC port
      - "8900:8900"  # WebSocket port
    volumes:
      - .:/app
    environment:
      - SOLANA_URL=http://localhost:8899
    command: solana-test-validator --reset

  tests:
    build: .
    depends_on:
      - validator
    volumes:
      - .:/app
    environment:
      - SOLANA_URL=http://validator:8899
    command: anchor test 